Traceback (most recent call last):
  File "/home/hleroy/Documents/UnivSID/DLA/TP1/src/train.py", line 83, in <module>
    main(args)
  File "/home/hleroy/Documents/UnivSID/DLA/TP1/src/train.py", line 69, in main
    train_model(model, train_loader, criterion, optimizer, args.num_epochs, args.save_path)
  File "/home/hleroy/Documents/UnivSID/DLA/TP1/src/train.py", line 33, in train_model
    outputs = model(images)
  File "/home/hleroy/.cache/pypoetry/virtualenvs/tp1-ftMjbHMZ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hleroy/.cache/pypoetry/virtualenvs/tp1-ftMjbHMZ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hleroy/Documents/UnivSID/DLA/TP1/models/model.py", line 31, in forward
    x = self.maxpool2(x)
  File "/home/hleroy/.cache/pypoetry/virtualenvs/tp1-ftMjbHMZ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CNN' object has no attribute 'maxpool2'
